version: '3.8'

services:
    blog-api:
#        build:
#            context: ./
#            dockerfile: Dockerfile.prod
        image: ghcr.io/pnlinh-it/blog-api:pr-5
        container_name: blog-api
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - "80:80"
        networks:
            - blog-api

networks:
    blog-api:
        driver: bridge
        name: blog-api
