version: '3.8'

services:
    blog-api:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        container_name: blog-api
        volumes:
            - .:/var/www/blog
        env_file:
            - .env
        environment:
            PHP_IDE_CONFIG: serverName=blog-local-docker
        restart: unless-stopped
        ports:
            - "80:80"
        networks:
            - blog-api

networks:
    blog-api:
        driver: bridge
        name: blog-api
