version: '3.8'

services:
    blog-api:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        image: blog-api
        container_name: blog-api
        env_file:
            - .env
        restart: unless-stopped
        ports:
            - "80:80"
        networks:
            - blog-api

networks:
    blog-api:
        driver: bridge
        name: blog-api
